name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install joblib
          pip install ruff black pytest
        
      - name: Test imports
        run: |
          python -c "import app; print('App imports successfully')"
          python -c "import model; print('Model imports successfully')"
          python -c "import random_forest_model; print('Random Forest model imports successfully')"
          python -c "import pdf_report; print('PDF report imports successfully')"
          python -c "import summarize; print('Summarize imports successfully')"
      
      - name: Run tests
        run: |
          python -c "from storage import init_db; init_db()"
          pytest -v
      
      - name: Test Docker build
        run: |
          docker build -t netops-ai-pipeline .
