name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
          echo "Checking out code..."
      
      - name: Setup Python
        run: |
          echo "Setting up Python..."
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Test imports
        run: |
          python -c "import app; print('App imports successfully')"
          python -c "import model; print('Model imports successfully')"
          python -c "import random_forest_model; print('Random Forest model imports successfully')"
          python -c "import pdf_report; print('PDF report imports successfully')"
          python -c "import summarize; print('Summarize imports successfully')"
      
      - name: Run tests
        run: |
          python -c "from storage import init_db; init_db()"
          pytest -v
